import Head from 'next/head'
import { useEffect, useState } from 'react';
import { ethers } from 'ethers'
import Profile from '../components/Profile';
import SendEth from '../components/SendEth';
import Transactions from '../components/Transactions';

export default function Home() {

  const [errorMessage, setErrorMessage] = useState(null);
  const [defaultAccount, setDefaultAccount] = useState(null);
  const [userBalance, setUserBalance] = useState(null);
  const [connButtonText, setConnButtonText] = useState('Connect Wallet');

  const connectWalletHandler = () => {
    if (window.ethereum && window.ethereum.isMetaMask) {
      console.log('MetaMask Here!');

      window.ethereum.request({ method: 'eth_requestAccounts' })
        .then(result => {
          accountChangedHandler(result[0]);
          setConnButtonText('Wallet Connected');
          getAccountBalance(result[0]);
        })
        .catch(error => {
          setErrorMessage(error.message);
        });

    } else {
      console.log('Need to install MetaMask');
      setErrorMessage('Please install MetaMask browser extension to interact');
    }
  }

  const accountChangedHandler = (newAccount) => {
    setDefaultAccount(newAccount);
    getAccountBalance(newAccount.toString());
  }

  const getAccountBalance = (account) => {
    window.ethereum.request({ method: 'eth_getBalance', params: [account, 'latest'] })
      .then(balance => {
        setUserBalance(ethers.utils.formatEther(balance));
      })
      .catch(error => {
        setErrorMessage(error.message);
      });
  };

  const chainChangedHandler = () => {
    // reload the page to avoid any errors with chain change mid use of application
    window.location.reload();
  }

  useEffect(() => {
    if (typeof window !== "undefined") {

      if (window.ethereum) {
        console.log('MetaMask Here!');
        window.ethereum.on('accountsChanged', accountChangedHandler);
        window.ethereum.on('chainChanged', chainChangedHandler);
      } else {
        console.log('Need to install MetaMask');
        setErrorMessage('Please install MetaMask browser extension to interact');
      }
    }
  }, [accountChangedHandler, chainChangedHandler])



  return (
    <div className="min-h-screen flex-col flex justify-center items-center">
      <Head>
        <title>First DAPP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {
        errorMessage && (
          <div className="alert alert-error mt-4">
            <div className="flex-1">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="w-6 h-6 mx-2 stroke-current">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636"></path>
              </svg>
              <label>{errorMessage}</label>
            </div>
          </div>
        )
      }

      <div className="flex justify-center items-center w-full container p-4">

        <div className='w-full'>
          <div className='flex justify-center'>
            <Profile defaultAccount={defaultAccount} userBalance={userBalance} errorMessage={errorMessage} connectWalletHandler={connectWalletHandler} connButtonText={connButtonText} />

            <SendEth />
          </div>

          <div className='mt-8'>
            <Transactions />
          </div>

        </div>

      </div>

      <footer className="fixed bottom-0 p-4 footer bg-base-100 border-t-2 border-base-200 text-base-content footer-center">
        <div>
          <p>Made with ❤️ by <span className='hover:underline font-bold cursor-pointer'>Mukul Rajpoot</span></p>
        </div>
      </footer>


    </div>
  )
}
